const fs = require("fs");
const { JsonRpcProvider, Wallet, Contract } = require("ethers");

const RPC_URL = "http://127.0.0.1:8545";
const VERIFIER_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";

// Hardhat Account #0
const PRIVATE_KEY =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

// Groth16 verifier ABI shape generated by snarkjs
const ABI = [
  "function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[5] calldata _pubSignals) external view returns (bool)"
];

function loadJson(path) {
  return JSON.parse(fs.readFileSync(path, "utf8"));
}

function toSolidityCallData(proof, publicSignals) {
  const pA = [proof.pi_a[0], proof.pi_a[1]];

  // Groth16 Solidity verifier expects B reversed per pair
  const pB = [
    [proof.pi_b[0][1], proof.pi_b[0][0]],
    [proof.pi_b[1][1], proof.pi_b[1][0]],
  ];

  const pC = [proof.pi_c[0], proof.pi_c[1]];

  const pubSignals = publicSignals.map(String);

  return { pA, pB, pC, pubSignals };
}

async function main() {
  const provider = new JsonRpcProvider(RPC_URL);
  const wallet = new Wallet(PRIVATE_KEY, provider);
  const verifier = new Contract(VERIFIER_ADDRESS, ABI, wallet);

  const proof = loadJson("circuits/build/auth_proof.json");
  const publicSignals = loadJson("circuits/build/auth_public.json");

  const { pA, pB, pC, pubSignals } = toSolidityCallData(proof, publicSignals);

  console.log("Calling verifier with:");
  console.log(JSON.stringify({ pA, pB, pC, pubSignals }, null, 2));

  const ok = await verifier.verifyProof(pA, pB, pC, pubSignals);

  console.log("\nOn-chain verification result:", ok);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});